using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.ComponentModel.__Internals;
using CommunityToolkit.Mvvm.Input;
using Launcher.App.Resources;
using Launcher.App.ViewModels.Shared;
using Launcher.Application.Services;
using Launcher.Domain.Models;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Logging.Abstractions;

namespace Launcher.App.ViewModels.Download;

public sealed class DownloadInstanceOptionsViewModel : ObservableObject, IDisposable
{
	private readonly IGameInstanceService instanceService;

	private readonly IReadOnlyDictionary<LoaderKind, ILoaderProvider> loaderProviders;

	private readonly IModrinthService? modrinthService;

	private readonly DownloadInstanceNameTracker instanceNameTracker;

	private readonly IInstanceInstallNameAvailabilityService? instanceInstallNameAvailabilityService;

	private readonly ILogger logger;

	private CancellationTokenSource? loaderRequestCancellation;

	private CancellationTokenSource? addonRequestCancellation;

	private CancellationTokenSource? nameAvailabilityCancellation;

	private DownloadMinecraftVersionItem? selectedMinecraftVersion;

	private DownloadSourcePreference downloadSourcePreference = DownloadSourcePreference.Official;

	private int downloadSpeedLimitMbPerSecond;

	private string lastAutoGeneratedInstanceName = string.Empty;

	private bool isUpdatingInstanceNameInternally;

	private bool isActive;

	private string externallyUnavailableInstanceName = string.Empty;

	private string minecraftDirectory = string.Empty;

	[ObservableProperty]
	private string instanceName = string.Empty;

	[ObservableProperty]
	private DownloadLoaderOption? selectedLoaderOption;

	[ObservableProperty]
	private LoaderVersionInfo? selectedLoaderVersion;

	[ObservableProperty]
	private bool isLoadingLoaderVersions;

	[ObservableProperty]
	private string loaderVersionLoadError = string.Empty;

	[ObservableProperty]
	private DownloadAddonLibraryVersionOption? selectedAddonLibraryVersion;

	[ObservableProperty]
	private bool isLoadingAddonLibraryVersions;

	[ObservableProperty]
	private string addonLibraryVersionLoadError = string.Empty;

	[ObservableProperty]
	private string instanceNameDuplicateMessage = string.Empty;

	[ObservableProperty]
	private bool isCheckingInstanceNameAvailability;

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.4.0.0")]
	private RelayCommand<DownloadLoaderOption>? selectLoaderOptionCommand;

	public ObservableCollection<DownloadLoaderOption> LoaderOptions { get; } = new ObservableCollection<DownloadLoaderOption>();

	public ObservableCollection<LoaderVersionInfo> LoaderVersions { get; } = new ObservableCollection<LoaderVersionInfo>();

	public ObservableCollection<DownloadAddonLibraryVersionOption> AddonLibraryVersions { get; } = new ObservableCollection<DownloadAddonLibraryVersionOption>();

	public ObservableCollection<DownloadAddonLibraryVersionOption> QuiltLibraryVersions => AddonLibraryVersions;

	public bool HasInstanceNameDuplicateMessage => !string.IsNullOrWhiteSpace(InstanceNameDuplicateMessage);

	public bool HasLoaderVersions => LoaderVersions.Count > 0;

	public bool HasNoLoaderVersions
	{
		get
		{
			if (!IsLoadingLoaderVersions && LoaderVersions.Count == 0 && string.IsNullOrWhiteSpace(LoaderVersionLoadError) && RequiresLoaderVersionSelection(SelectedLoaderOption?.Kind))
			{
				return isActive;
			}
			return false;
		}
	}

	public bool HasLoaderVersionLoadError => !string.IsNullOrWhiteSpace(LoaderVersionLoadError);

	public bool ShouldShowLoaderVersionSelector
	{
		get
		{
			if (isActive)
			{
				return RequiresLoaderVersionSelection(SelectedLoaderOption?.Kind);
			}
			return false;
		}
	}

	public bool ShouldShowAddonLibrarySelector
	{
		get
		{
			if (isActive)
			{
				return SupportsAddonLibrarySelection(SelectedLoaderOption?.Kind);
			}
			return false;
		}
	}

	public bool ShouldShowQuiltLibrarySelector
	{
		get
		{
			if (ShouldShowAddonLibrarySelector)
			{
				LoaderKind? loaderKind = SelectedLoaderOption?.Kind;
				if (loaderKind.HasValue)
				{
					return loaderKind == LoaderKind.Quilt;
				}
				return false;
			}
			return false;
		}
	}

	public bool HasAddonLibraryVersions => AddonLibraryVersions.Count > 0;

	public bool HasQuiltLibraryVersions => HasAddonLibraryVersions;

	public bool HasAddonLibraryVersionLoadError => !string.IsNullOrWhiteSpace(AddonLibraryVersionLoadError);

	public bool HasQuiltLibraryVersionLoadError => HasAddonLibraryVersionLoadError;

	public bool IsAddonLibraryVersionSelectorEnabled
	{
		get
		{
			if (!IsLoadingAddonLibraryVersions)
			{
				return HasAddonLibraryVersions;
			}
			return false;
		}
	}

	public bool IsQuiltLibraryVersionSelectorEnabled => IsAddonLibraryVersionSelectorEnabled;

	public bool IsLoadingQuiltLibraryVersions => IsLoadingAddonLibraryVersions;

	public string AddonLibraryLabelText => SelectedLoaderOption?.Kind switch
	{
		LoaderKind.Fabric => Strings.Download_FabricApiLabel, 
		LoaderKind.Quilt => Strings.Download_QuiltLibraryLabel, 
		_ => string.Empty, 
	};

	public string LoaderVersionPlaceholderText
	{
		get
		{
			if (!IsLoadingLoaderVersions)
			{
				if (!HasLoaderVersionLoadError)
				{
					if (!HasNoLoaderVersions)
					{
						return Strings.Download_SelectVersionPlaceholder;
					}
					return string.Format(Strings.Download_LoaderVersionEmptyFormat, GetSelectedLoaderTitle());
				}
				return Strings.Download_LoaderVersionLoadFailedShort;
			}
			return string.Format(Strings.Status_LoadingLoaderVersionsFormat, GetSelectedLoaderTitle());
		}
	}

	public string AddonLibraryVersionPlaceholderText
	{
		get
		{
			if (!IsLoadingAddonLibraryVersions)
			{
				if (!HasAddonLibraryVersionLoadError)
				{
					if (HasAddonLibraryVersions)
					{
						return string.Empty;
					}
					return Strings.Download_AddonLibraryEmpty;
				}
				return Strings.Download_AddonLibraryLoadFailedShort;
			}
			return Strings.Download_AddonLibraryLoading;
		}
	}

	public string QuiltLibraryVersionPlaceholderText => AddonLibraryVersionPlaceholderText;

	public DownloadAddonLibraryVersionOption? SelectedQuiltLibraryVersion
	{
		get
		{
			return SelectedAddonLibraryVersion;
		}
		set
		{
			SelectedAddonLibraryVersion = value;
		}
	}

	public string QuiltLibraryVersionLoadError => AddonLibraryVersionLoadError;

	public bool CanInstall
	{
		get
		{
			if (isActive && selectedMinecraftVersion != null && CanInstallSelectedLoader() && !string.IsNullOrWhiteSpace(InstanceName) && !IsCheckingInstanceNameAvailability)
			{
				return !HasInstanceNameDuplicateMessage;
			}
			return false;
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public string InstanceName
	{
		get
		{
			return instanceName;
		}
		[MemberNotNull("instanceName")]
		set
		{
			if (!EqualityComparer<string>.Default.Equals(instanceName, value))
			{
				OnPropertyChanging(__KnownINotifyPropertyChangingArgs.InstanceName);
				instanceName = value;
				OnInstanceNameChanged(value);
				OnPropertyChanged(__KnownINotifyPropertyChangedArgs.InstanceName);
			}
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public DownloadLoaderOption? SelectedLoaderOption
	{
		get
		{
			return selectedLoaderOption;
		}
		set
		{
			if (!EqualityComparer<DownloadLoaderOption>.Default.Equals(selectedLoaderOption, value))
			{
				OnPropertyChanging(__KnownINotifyPropertyChangingArgs.SelectedLoaderOption);
				selectedLoaderOption = value;
				OnSelectedLoaderOptionChanged(value);
				OnPropertyChanged(__KnownINotifyPropertyChangedArgs.SelectedLoaderOption);
			}
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public LoaderVersionInfo? SelectedLoaderVersion
	{
		get
		{
			return selectedLoaderVersion;
		}
		set
		{
			if (!EqualityComparer<LoaderVersionInfo>.Default.Equals(selectedLoaderVersion, value))
			{
				OnPropertyChanging(__KnownINotifyPropertyChangingArgs.SelectedLoaderVersion);
				selectedLoaderVersion = value;
				OnSelectedLoaderVersionChanged(value);
				OnPropertyChanged(__KnownINotifyPropertyChangedArgs.SelectedLoaderVersion);
			}
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public bool IsLoadingLoaderVersions
	{
		get
		{
			return isLoadingLoaderVersions;
		}
		set
		{
			if (!EqualityComparer<bool>.Default.Equals(isLoadingLoaderVersions, value))
			{
				OnPropertyChanging(__KnownINotifyPropertyChangingArgs.IsLoadingLoaderVersions);
				isLoadingLoaderVersions = value;
				OnIsLoadingLoaderVersionsChanged(value);
				OnPropertyChanged(__KnownINotifyPropertyChangedArgs.IsLoadingLoaderVersions);
			}
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public string LoaderVersionLoadError
	{
		get
		{
			return loaderVersionLoadError;
		}
		[MemberNotNull("loaderVersionLoadError")]
		set
		{
			if (!EqualityComparer<string>.Default.Equals(loaderVersionLoadError, value))
			{
				OnPropertyChanging(__KnownINotifyPropertyChangingArgs.LoaderVersionLoadError);
				loaderVersionLoadError = value;
				OnLoaderVersionLoadErrorChanged(value);
				OnPropertyChanged(__KnownINotifyPropertyChangedArgs.LoaderVersionLoadError);
			}
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public DownloadAddonLibraryVersionOption? SelectedAddonLibraryVersion
	{
		get
		{
			return selectedAddonLibraryVersion;
		}
		set
		{
			if (!EqualityComparer<DownloadAddonLibraryVersionOption>.Default.Equals(selectedAddonLibraryVersion, value))
			{
				OnPropertyChanging(__KnownINotifyPropertyChangingArgs.SelectedAddonLibraryVersion);
				selectedAddonLibraryVersion = value;
				OnSelectedAddonLibraryVersionChanged(value);
				OnPropertyChanged(__KnownINotifyPropertyChangedArgs.SelectedAddonLibraryVersion);
			}
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public bool IsLoadingAddonLibraryVersions
	{
		get
		{
			return isLoadingAddonLibraryVersions;
		}
		set
		{
			if (!EqualityComparer<bool>.Default.Equals(isLoadingAddonLibraryVersions, value))
			{
				OnPropertyChanging(__KnownINotifyPropertyChangingArgs.IsLoadingAddonLibraryVersions);
				isLoadingAddonLibraryVersions = value;
				OnIsLoadingAddonLibraryVersionsChanged(value);
				OnPropertyChanged(__KnownINotifyPropertyChangedArgs.IsLoadingAddonLibraryVersions);
			}
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public string AddonLibraryVersionLoadError
	{
		get
		{
			return addonLibraryVersionLoadError;
		}
		[MemberNotNull("addonLibraryVersionLoadError")]
		set
		{
			if (!EqualityComparer<string>.Default.Equals(addonLibraryVersionLoadError, value))
			{
				OnPropertyChanging(__KnownINotifyPropertyChangingArgs.AddonLibraryVersionLoadError);
				addonLibraryVersionLoadError = value;
				OnAddonLibraryVersionLoadErrorChanged(value);
				OnPropertyChanged(__KnownINotifyPropertyChangedArgs.AddonLibraryVersionLoadError);
			}
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public string InstanceNameDuplicateMessage
	{
		get
		{
			return instanceNameDuplicateMessage;
		}
		[MemberNotNull("instanceNameDuplicateMessage")]
		set
		{
			if (!EqualityComparer<string>.Default.Equals(instanceNameDuplicateMessage, value))
			{
				OnPropertyChanging(__KnownINotifyPropertyChangingArgs.InstanceNameDuplicateMessage);
				instanceNameDuplicateMessage = value;
				OnInstanceNameDuplicateMessageChanged(value);
				OnPropertyChanged(__KnownINotifyPropertyChangedArgs.InstanceNameDuplicateMessage);
			}
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public bool IsCheckingInstanceNameAvailability
	{
		get
		{
			return isCheckingInstanceNameAvailability;
		}
		set
		{
			if (!EqualityComparer<bool>.Default.Equals(isCheckingInstanceNameAvailability, value))
			{
				OnPropertyChanging(__KnownINotifyPropertyChangingArgs.IsCheckingInstanceNameAvailability);
				isCheckingInstanceNameAvailability = value;
				OnIsCheckingInstanceNameAvailabilityChanged(value);
				OnPropertyChanged(__KnownINotifyPropertyChangedArgs.IsCheckingInstanceNameAvailability);
			}
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.RelayCommandGenerator", "8.4.0.0")]
	[ExcludeFromCodeCoverage]
	public IRelayCommand<DownloadLoaderOption> SelectLoaderOptionCommand => selectLoaderOptionCommand ?? (selectLoaderOptionCommand = new RelayCommand<DownloadLoaderOption>(SelectLoaderOption));

	public event Action? InstallAvailabilityChanged;

	internal DownloadInstanceOptionsViewModel(IGameInstanceService instanceService, IEnumerable<ILoaderProvider> loaderProviders, DownloadInstanceNameTracker instanceNameTracker, IInstanceInstallNameAvailabilityService? instanceInstallNameAvailabilityService = null, IModrinthService? modrinthService = null, ILogger? logger = null)
	{
		this.instanceService = instanceService;
		this.loaderProviders = loaderProviders.ToDictionary((ILoaderProvider provider) => provider.Kind);
		this.instanceNameTracker = instanceNameTracker;
		this.instanceInstallNameAvailabilityService = instanceInstallNameAvailabilityService;
		this.modrinthService = modrinthService;
		this.logger = logger ?? NullLogger.Instance;
		LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Vanilla, Strings.Download_VanillaLoaderTitle, Strings.Download_VanillaLoaderSubtitle, string.Empty, StartRide.Core.BrandingIcons.BeamNgLogo));
		LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Fabric, Strings.Download_FabricLoaderTitle, Strings.Download_FabricLoaderSubtitle, "\ue8b7", "/Assets/Icons/block/fabric.png"));
		LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Forge, Strings.Download_ForgeLoaderTitle, Strings.Download_ForgeLoaderSubtitle, "\ue8b7", "/Assets/Icons/block/Anvil.png"));
		LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.NeoForge, Strings.Download_NeoForgeLoaderTitle, Strings.Download_NeoForgeLoaderSubtitle, "\ue8b7", "/Assets/Icons/block/neo_logo.png"));
		LoaderOptions.Add(new DownloadLoaderOption(LoaderKind.Quilt, Strings.Download_QuiltLoaderTitle, Strings.Download_QuiltLoaderSubtitle, "\ue8b7", "/Assets/Icons/block/quilt_x16.png"));
		LoaderVersions.CollectionChanged += delegate
		{
			NotifyLoaderCollectionChanged();
		};
		AddonLibraryVersions.CollectionChanged += delegate
		{
			NotifyAddonCollectionChanged();
		};
		SelectedLoaderOption = LoaderOptions[0];
	}

	public async Task PrepareAsync(DownloadMinecraftVersionItem minecraftVersion, CancellationToken cancellationToken = default(CancellationToken))
	{
		isActive = true;
		selectedMinecraftVersion = minecraftVersion;
		ResetLoaderVersionState();
		ResetAddonLibraryVersionState();
		SelectedLoaderOption = LoaderOptions.First((DownloadLoaderOption option) => option.Kind == LoaderKind.Vanilla);
		ApplyAutoGeneratedInstanceName(force: true);
		await RefreshExistingInstanceNamesAsync(cancellationToken);
		NotifyStateChanged();
	}

	public void Deactivate()
	{
		isActive = false;
		selectedMinecraftVersion = null;
		CancelRequests();
		ResetLoaderVersionState();
		ResetAddonLibraryVersionState();
		lastAutoGeneratedInstanceName = string.Empty;
		NotifyStateChanged();
	}

	public void ApplyDownloadSourcePreference(DownloadSourcePreference preference)
	{
		if (downloadSourcePreference != preference)
		{
			downloadSourcePreference = preference;
			if (isActive)
			{
				RefreshLoaderVersionsForSelectionAsync(SelectedLoaderOption);
				RefreshAddonLibraryVersionsForSelectionAsync(SelectedLoaderOption);
			}
		}
	}

	public void ApplyDownloadSpeedLimit(int value)
	{
		downloadSpeedLimitMbPerSecond = Math.Max(value, 0);
	}

	public DownloadInstallRequest? CreateInstallRequest()
	{
		if (!CanInstall || selectedMinecraftVersion == null)
		{
			return null;
		}
		DownloadLoaderOption downloadLoaderOption = SelectedLoaderOption ?? LoaderOptions[0];
		string text = (string.IsNullOrWhiteSpace(InstanceName) ? selectedMinecraftVersion.Name : InstanceName.Trim());
		return new DownloadInstallRequest(selectedMinecraftVersion.Name, selectedMinecraftVersion.Type, text, downloadLoaderOption.Kind, (downloadLoaderOption.Kind == LoaderKind.Vanilla) ? null : SelectedLoaderVersion?.Version, (downloadLoaderOption.Kind != LoaderKind.Fabric) ? null : SelectedAddonLibraryVersion?.VersionId, (downloadLoaderOption.Kind != LoaderKind.Quilt) ? null : SelectedAddonLibraryVersion?.VersionId, GetSelectedLoaderDisplayName(), downloadSourcePreference, downloadSpeedLimitMbPerSecond);
	}

	public void ApplyMinecraftDirectory(string? directory)
	{
		string b = directory?.Trim() ?? string.Empty;
		if (!string.Equals(minecraftDirectory, b, StringComparison.Ordinal))
		{
			minecraftDirectory = b;
			RequestInstanceNameAvailabilityCheck();
		}
	}

	public void NotifyNameAvailabilityChanged()
	{
		RequestInstanceNameAvailabilityCheck();
	}

	public async Task RefreshNameAvailabilityAsync(CancellationToken cancellationToken = default(CancellationToken))
	{
		if (isActive)
		{
			await RefreshExistingInstanceNamesAsync(cancellationToken);
		}
	}

	public void Dispose()
	{
		CancelRequests();
	}

	[RelayCommand]
	private void SelectLoaderOption(DownloadLoaderOption loaderOption)
	{
		SelectedLoaderOption = loaderOption;
	}

	private async Task RefreshLoaderVersionsForSelectionAsync(DownloadLoaderOption? loaderOption)
	{
		CancellationTokenSource cancellation = ReplaceLoaderRequestCancellation();
		if (!RequiresLoaderVersionSelection(loaderOption?.Kind) || selectedMinecraftVersion == null || !isActive)
		{
			ResetLoaderVersionState(cancelRequest: false);
			ReleaseLoaderCancellation(cancellation);
			return;
		}
		if (!loaderProviders.TryGetValue(loaderOption.Kind, out ILoaderProvider value) || !value.IsImplemented)
		{
			ResetLoaderVersionState(cancelRequest: false);
			ReleaseLoaderCancellation(cancellation);
			return;
		}
		string requestedVersion = selectedMinecraftVersion.Name;
		LoaderVersionLoadError = string.Empty;
		IsLoadingLoaderVersions = true;
		LoaderVersions.Clear();
		SelectedLoaderVersion = null;
		try
		{
			IReadOnlyList<LoaderVersionInfo> items = await value.GetLoaderVersionsAsync(requestedVersion, downloadSourcePreference, cancellation.Token, downloadSpeedLimitMbPerSecond);
			if (IsLoaderRequestCurrent(cancellation, loaderOption, requestedVersion))
			{
				LoaderVersions.ReplaceWith(items);
				SelectedLoaderVersion = null;
				ApplyAutoGeneratedInstanceName(force: false);
			}
		}
		catch (OperationCanceledException) when (cancellation.IsCancellationRequested)
		{
		}
		catch (Exception exception)
		{
			logger.LogWarning(exception, "Failed to load loader versions. MinecraftVersion={MinecraftVersion} Loader={Loader}", requestedVersion, loaderOption.Kind);
			if (IsLoaderRequestCurrent(cancellation, loaderOption, requestedVersion))
			{
				LoaderVersionLoadError = string.Format(Strings.Status_LoaderVersionsLoadFailedFormat, loaderOption.Title);
			}
		}
		finally
		{
			if (IsLoaderRequestCurrent(cancellation, loaderOption, requestedVersion))
			{
				IsLoadingLoaderVersions = false;
			}
			ReleaseLoaderCancellation(cancellation);
		}
	}

	private async Task RefreshAddonLibraryVersionsForSelectionAsync(DownloadLoaderOption? loaderOption)
	{
		CancellationTokenSource cancellation = ReplaceAddonRequestCancellation();
		if (!SupportsAddonLibrarySelection(loaderOption?.Kind) || selectedMinecraftVersion == null || !isActive)
		{
			ResetAddonLibraryVersionState(cancelRequest: false);
			ReleaseAddonCancellation(cancellation);
			return;
		}
		string requestedVersion = selectedMinecraftVersion.Name;
		AddonLibraryVersionLoadError = string.Empty;
		IsLoadingAddonLibraryVersions = true;
		ClearAddonLibraryVersionOptions();
		if (modrinthService == null)
		{
			IsLoadingAddonLibraryVersions = false;
			ReleaseAddonCancellation(cancellation);
			return;
		}
		try
		{
			IReadOnlyList<ModrinthVersionInfo> readOnlyList = await GetAddonLibraryVersionsAsync(loaderOption.Kind, requestedVersion, cancellation.Token);
			if (!IsAddonRequestCurrent(cancellation, loaderOption, requestedVersion))
			{
				return;
			}
			AddonLibraryVersions.Add(DownloadAddonLibraryVersionOption.None);
			bool isLatest = true;
			foreach (ModrinthVersionInfo item in readOnlyList)
			{
				AddonLibraryVersions.Add(DownloadAddonLibraryVersionOption.FromVersion(item, isLatest));
				isLatest = false;
			}
			SelectedAddonLibraryVersion = AddonLibraryVersions.FirstOrDefault((DownloadAddonLibraryVersionOption option) => option.IsInstallable) ?? AddonLibraryVersions.FirstOrDefault();
		}
		catch (OperationCanceledException) when (cancellation.IsCancellationRequested)
		{
		}
		catch (Exception exception)
		{
			logger.LogWarning(exception, "Failed to load optional loader library versions. MinecraftVersion={MinecraftVersion} Loader={Loader}", requestedVersion, loaderOption.Kind);
			if (IsAddonRequestCurrent(cancellation, loaderOption, requestedVersion))
			{
				ClearAddonLibraryVersionOptions();
				AddonLibraryVersionLoadError = GetAddonLibraryVersionLoadFailedMessage(loaderOption.Kind);
			}
		}
		finally
		{
			if (IsAddonRequestCurrent(cancellation, loaderOption, requestedVersion))
			{
				IsLoadingAddonLibraryVersions = false;
			}
			ReleaseAddonCancellation(cancellation);
		}
	}

	private async Task RefreshExistingInstanceNamesAsync(CancellationToken cancellationToken)
	{
		DownloadInstanceNameTracker downloadInstanceNameTracker = instanceNameTracker;
		downloadInstanceNameTracker.ReplaceExisting(await instanceService.GetInstancesAsync(cancellationToken));
		await CheckInstanceNameAvailabilityAsync(InstanceName, debounce: false, cancellationToken);
	}

	private void RefreshInstanceNameDuplicateMessage()
	{
		string text = InstanceName?.Trim() ?? string.Empty;
		InstanceNameDuplicateMessage = ((!string.IsNullOrWhiteSpace(text) && (instanceNameTracker.IsUnavailable(text) || string.Equals(externallyUnavailableInstanceName, text, StringComparison.OrdinalIgnoreCase))) ? Strings.Status_DuplicateInstanceName : string.Empty);
	}

	private void RequestInstanceNameAvailabilityCheck()
	{
		externallyUnavailableInstanceName = string.Empty;
		RefreshInstanceNameDuplicateMessage();
		string value = InstanceName?.Trim() ?? string.Empty;
		if (!isActive || instanceInstallNameAvailabilityService == null || string.IsNullOrEmpty(minecraftDirectory) || !VersionDirectoryName.IsSafeDirectoryName(value))
		{
			CancelNameAvailabilityRequest();
		}
		else
		{
			CheckInstanceNameAvailabilityAsync(value, debounce: true, CancellationToken.None);
		}
	}

	private async Task CheckInstanceNameAvailabilityAsync(string? instanceName, bool debounce, CancellationToken cancellationToken)
	{
		string normalizedName = instanceName?.Trim() ?? string.Empty;
		if (instanceInstallNameAvailabilityService == null || string.IsNullOrEmpty(minecraftDirectory) || !VersionDirectoryName.IsSafeDirectoryName(normalizedName))
		{
			CancelNameAvailabilityRequest();
			RefreshInstanceNameDuplicateMessage();
			return;
		}
		CancellationTokenSource requestCancellation = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken);
		Interlocked.Exchange(ref nameAvailabilityCancellation, requestCancellation)?.Cancel();
		IsCheckingInstanceNameAvailability = true;
		try
		{
			if (debounce)
			{
				await Task.Delay(TimeSpan.FromMilliseconds(120.0), requestCancellation.Token);
			}
			InstanceInstallNameAvailability instanceInstallNameAvailability = await instanceInstallNameAvailabilityService.CheckAsync(minecraftDirectory, normalizedName, requestCancellation.Token);
			if (IsNameAvailabilityRequestCurrent(requestCancellation, normalizedName))
			{
				externallyUnavailableInstanceName = ((instanceInstallNameAvailability == InstanceInstallNameAvailability.Occupied) ? normalizedName : string.Empty);
				RefreshInstanceNameDuplicateMessage();
			}
		}
		catch (OperationCanceledException) when (requestCancellation.IsCancellationRequested)
		{
		}
		catch (Exception exception)
		{
			if (IsNameAvailabilityRequestCurrent(requestCancellation, normalizedName))
			{
				externallyUnavailableInstanceName = string.Empty;
				RefreshInstanceNameDuplicateMessage();
			}
			logger.LogWarning(exception, "Failed to refresh Minecraft instance name availability. InstanceName={InstanceName}", normalizedName);
		}
		finally
		{
			if (Interlocked.CompareExchange(ref nameAvailabilityCancellation, null, requestCancellation) == requestCancellation)
			{
				IsCheckingInstanceNameAvailability = false;
			}
			requestCancellation.Dispose();
		}
	}

	private bool IsNameAvailabilityRequestCurrent(CancellationTokenSource requestCancellation, string instanceName)
	{
		if (nameAvailabilityCancellation == requestCancellation && isActive)
		{
			return string.Equals(InstanceName?.Trim(), instanceName, StringComparison.OrdinalIgnoreCase);
		}
		return false;
	}

	private void CancelNameAvailabilityRequest()
	{
		Interlocked.Exchange(ref nameAvailabilityCancellation, null)?.Cancel();
		IsCheckingInstanceNameAvailability = false;
	}

	private void ApplyAutoGeneratedInstanceName(bool force)
	{
		string value = CreateSuggestedInstanceName();
		if (string.IsNullOrWhiteSpace(value))
		{
			return;
		}
		string text = InstanceName?.Trim() ?? string.Empty;
		if (!force && !string.IsNullOrWhiteSpace(text) && !string.Equals(text, lastAutoGeneratedInstanceName, StringComparison.OrdinalIgnoreCase))
		{
			return;
		}
		isUpdatingInstanceNameInternally = true;
		try
		{
			InstanceName = value;
			lastAutoGeneratedInstanceName = value;
		}
		finally
		{
			isUpdatingInstanceNameInternally = false;
		}
	}

	private string CreateSuggestedInstanceName()
	{
		string text = selectedMinecraftVersion?.Name?.Trim();
		if (string.IsNullOrWhiteSpace(text))
		{
			return string.Empty;
		}
		string text2 = SelectedLoaderVersion?.Version;
		switch (SelectedLoaderOption?.Kind)
		{
		case LoaderKind.Fabric:
			if (!string.IsNullOrWhiteSpace(text2))
			{
				return text + "-fabric-" + text2;
			}
			return text + "-fabric";
		case LoaderKind.Forge:
			if (!string.IsNullOrWhiteSpace(text2))
			{
				return text + "-forge-" + text2;
			}
			return text + "-forge";
		case LoaderKind.NeoForge:
			if (!string.IsNullOrWhiteSpace(text2))
			{
				return text + "-neoforge-" + text2;
			}
			return text + "-neoforge";
		case LoaderKind.Quilt:
			if (!string.IsNullOrWhiteSpace(text2))
			{
				return text + "-quilt-" + text2;
			}
			return text + "-quilt";
		default:
			return text;
		}
	}

	private bool CanInstallSelectedLoader()
	{
		LoaderKind? loaderKind = SelectedLoaderOption?.Kind;
		if (loaderKind.HasValue)
		{
			LoaderKind valueOrDefault = loaderKind.GetValueOrDefault();
			if (valueOrDefault == LoaderKind.Vanilla)
			{
				return true;
			}
			if (RequiresLoaderVersionSelection(valueOrDefault))
			{
				return !IsLoadingLoaderVersions && (!SupportsAddonLibrarySelection(valueOrDefault) || !IsLoadingAddonLibraryVersions) && string.IsNullOrWhiteSpace(LoaderVersionLoadError) && (object)SelectedLoaderVersion != null;
			}
		}
		return false;
	}

	private string GetSelectedLoaderDisplayName()
	{
		string text = SelectedLoaderVersion?.Version;
		if (RequiresLoaderVersionSelection(SelectedLoaderOption?.Kind) && !string.IsNullOrWhiteSpace(text))
		{
			return GetSelectedLoaderTitle() + " " + text;
		}
		return GetSelectedLoaderTitle();
	}

	private string GetSelectedLoaderTitle()
	{
		return SelectedLoaderOption?.Title ?? Strings.Download_VanillaLoaderTitle;
	}

	private Task<IReadOnlyList<ModrinthVersionInfo>> GetAddonLibraryVersionsAsync(LoaderKind loaderKind, string minecraftVersion, CancellationToken cancellationToken)
	{
		return loaderKind switch
		{
			LoaderKind.Fabric => modrinthService.GetFabricApiVersionsAsync(minecraftVersion, cancellationToken), 
			LoaderKind.Quilt => modrinthService.GetQuiltStandardLibraryVersionsAsync(minecraftVersion, cancellationToken), 
			_ => Task.FromResult((IReadOnlyList<ModrinthVersionInfo>)Array.Empty<ModrinthVersionInfo>()), 
		};
	}

	private static string GetAddonLibraryVersionLoadFailedMessage(LoaderKind loaderKind)
	{
		return loaderKind switch
		{
			LoaderKind.Fabric => Strings.Status_FabricApiVersionsLoadFailed, 
			LoaderKind.Quilt => Strings.Status_QuiltLibraryVersionsLoadFailed, 
			_ => string.Empty, 
		};
	}

	private CancellationTokenSource ReplaceLoaderRequestCancellation()
	{
		CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
		Interlocked.Exchange(ref loaderRequestCancellation, cancellationTokenSource)?.Cancel();
		return cancellationTokenSource;
	}

	private CancellationTokenSource ReplaceAddonRequestCancellation()
	{
		CancellationTokenSource cancellationTokenSource = new CancellationTokenSource();
		Interlocked.Exchange(ref addonRequestCancellation, cancellationTokenSource)?.Cancel();
		return cancellationTokenSource;
	}

	private void ReleaseLoaderCancellation(CancellationTokenSource cancellation)
	{
		Interlocked.CompareExchange(ref loaderRequestCancellation, null, cancellation);
		cancellation.Dispose();
	}

	private void ReleaseAddonCancellation(CancellationTokenSource cancellation)
	{
		Interlocked.CompareExchange(ref addonRequestCancellation, null, cancellation);
		cancellation.Dispose();
	}

	private bool IsLoaderRequestCurrent(CancellationTokenSource cancellation, DownloadLoaderOption loaderOption, string minecraftVersion)
	{
		if (loaderRequestCancellation == cancellation && SelectedLoaderOption == loaderOption && string.Equals(selectedMinecraftVersion?.Name, minecraftVersion, StringComparison.Ordinal))
		{
			return isActive;
		}
		return false;
	}

	private bool IsAddonRequestCurrent(CancellationTokenSource cancellation, DownloadLoaderOption loaderOption, string minecraftVersion)
	{
		if (addonRequestCancellation == cancellation && SelectedLoaderOption == loaderOption && string.Equals(selectedMinecraftVersion?.Name, minecraftVersion, StringComparison.Ordinal))
		{
			return isActive;
		}
		return false;
	}

	private void ResetLoaderVersionState(bool cancelRequest = true)
	{
		if (cancelRequest)
		{
			Interlocked.Exchange(ref loaderRequestCancellation, null)?.Cancel();
		}
		LoaderVersions.Clear();
		SelectedLoaderVersion = null;
		IsLoadingLoaderVersions = false;
		LoaderVersionLoadError = string.Empty;
		OnPropertyChanged("LoaderVersionPlaceholderText");
	}

	private void ResetAddonLibraryVersionState(bool cancelRequest = true)
	{
		if (cancelRequest)
		{
			Interlocked.Exchange(ref addonRequestCancellation, null)?.Cancel();
		}
		IsLoadingAddonLibraryVersions = false;
		AddonLibraryVersionLoadError = string.Empty;
		ClearAddonLibraryVersionOptions();
	}

	private void ClearAddonLibraryVersionOptions()
	{
		AddonLibraryVersions.Clear();
		SelectedAddonLibraryVersion = null;
	}

	private void CancelRequests()
	{
		Interlocked.Exchange(ref loaderRequestCancellation, null)?.Cancel();
		Interlocked.Exchange(ref addonRequestCancellation, null)?.Cancel();
		CancelNameAvailabilityRequest();
	}

	private void NotifyLoaderCollectionChanged()
	{
		OnPropertyChanged("HasLoaderVersions");
		OnPropertyChanged("HasNoLoaderVersions");
		OnPropertyChanged("LoaderVersionPlaceholderText");
	}

	private void NotifyAddonCollectionChanged()
	{
		OnPropertyChanged("HasAddonLibraryVersions");
		OnPropertyChanged("IsAddonLibraryVersionSelectorEnabled");
		OnPropertyChanged("AddonLibraryVersionPlaceholderText");
		NotifyQuiltLibraryAliasPropertiesChanged();
	}

	private void NotifyQuiltLibraryAliasPropertiesChanged()
	{
		OnPropertyChanged("QuiltLibraryVersions");
		OnPropertyChanged("SelectedQuiltLibraryVersion");
		OnPropertyChanged("HasQuiltLibraryVersions");
		OnPropertyChanged("HasQuiltLibraryVersionLoadError");
		OnPropertyChanged("IsQuiltLibraryVersionSelectorEnabled");
		OnPropertyChanged("IsLoadingQuiltLibraryVersions");
		OnPropertyChanged("QuiltLibraryVersionPlaceholderText");
		OnPropertyChanged("QuiltLibraryVersionLoadError");
	}

	private void NotifyStateChanged()
	{
		OnPropertyChanged("CanInstall");
		InstallAvailabilityChanged?.Invoke();
	}

	private static bool RequiresLoaderVersionSelection(LoaderKind? loaderKind)
	{
		if (loaderKind.HasValue)
		{
			LoaderKind valueOrDefault = loaderKind.GetValueOrDefault();
			if ((uint)(valueOrDefault - 1) <= 3u)
			{
				return true;
			}
		}
		return false;
	}

	private static bool SupportsAddonLibrarySelection(LoaderKind? loaderKind)
	{
		switch (loaderKind)
		{
		case LoaderKind.Fabric:
		case LoaderKind.Quilt:
			return true;
		default:
			return false;
		}
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	private void OnInstanceNameChanged(string value)
	{
		RequestInstanceNameAvailabilityCheck();
		if (!isUpdatingInstanceNameInternally && string.IsNullOrWhiteSpace(value?.Trim()))
		{
			lastAutoGeneratedInstanceName = string.Empty;
		}
		NotifyStateChanged();
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	private void OnSelectedLoaderOptionChanged(DownloadLoaderOption? value)
	{
		foreach (DownloadLoaderOption loaderOption in LoaderOptions)
		{
			loaderOption.IsSelected = loaderOption == value;
		}
		OnPropertyChanged("HasNoLoaderVersions");
		OnPropertyChanged("ShouldShowLoaderVersionSelector");
		OnPropertyChanged("ShouldShowAddonLibrarySelector");
		OnPropertyChanged("ShouldShowQuiltLibrarySelector");
		OnPropertyChanged("AddonLibraryLabelText");
		ApplyAutoGeneratedInstanceName(force: false);
		RefreshLoaderVersionsForSelectionAsync(value);
		RefreshAddonLibraryVersionsForSelectionAsync(value);
		NotifyStateChanged();
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	private void OnSelectedLoaderVersionChanged(LoaderVersionInfo? value)
	{
		ApplyAutoGeneratedInstanceName(force: false);
		NotifyStateChanged();
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	private void OnIsLoadingLoaderVersionsChanged(bool value)
	{
		OnPropertyChanged("HasNoLoaderVersions");
		OnPropertyChanged("LoaderVersionPlaceholderText");
		NotifyStateChanged();
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	private void OnLoaderVersionLoadErrorChanged(string value)
	{
		OnPropertyChanged("HasNoLoaderVersions");
		OnPropertyChanged("HasLoaderVersionLoadError");
		OnPropertyChanged("LoaderVersionPlaceholderText");
		NotifyStateChanged();
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	private void OnSelectedAddonLibraryVersionChanged(DownloadAddonLibraryVersionOption? value)
	{
		NotifyQuiltLibraryAliasPropertiesChanged();
		NotifyStateChanged();
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	private void OnIsLoadingAddonLibraryVersionsChanged(bool value)
	{
		OnPropertyChanged("IsAddonLibraryVersionSelectorEnabled");
		OnPropertyChanged("AddonLibraryVersionPlaceholderText");
		NotifyQuiltLibraryAliasPropertiesChanged();
		NotifyStateChanged();
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	private void OnAddonLibraryVersionLoadErrorChanged(string value)
	{
		OnPropertyChanged("HasAddonLibraryVersionLoadError");
		OnPropertyChanged("AddonLibraryVersionPlaceholderText");
		NotifyQuiltLibraryAliasPropertiesChanged();
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	private void OnInstanceNameDuplicateMessageChanged(string value)
	{
		OnPropertyChanged("HasInstanceNameDuplicateMessage");
		NotifyStateChanged();
	}

	[GeneratedCode("CommunityToolkit.Mvvm.SourceGenerators.ObservablePropertyGenerator", "8.4.0.0")]
	private void OnIsCheckingInstanceNameAvailabilityChanged(bool value)
	{
		NotifyStateChanged();
	}
}
